spring:
  jpa:
    datasource:
      platform: h2
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    flyway:
      locations:
        - classpath:db/migration
  docker:
    compose:
      enabled: false
todo:
  duedate:
    cron:
      intervalInMillisecond: 1800000 #30 minutes